/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bgenvwieabtxwzapgeee"
export const publicAnonKey = "YOUR_SUPABASE_ANON_KEY_HERE"

// Supabase URL
export const supabaseUrl = "https://bgenvwieabtxwzapgeee.supabase.co"

// Option 2: Local authentication fallback
export const useLocalAuth = true