/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bgenvwieabtxwzapgeee"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZW52d2llYWJ0eHd6YXBnZWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjUzOTUsImV4cCI6MjA2OTI0MTM5NX0.jAkplpFSAAKqEMtFSZBFgluF_Obe6_upZA9W8uPtUIE"

// Supabase URL
export const supabaseUrl = "https://bgenvwieabtxwzapgeee.supabase.co"

// Option 2: Local authentication fallback
export const useLocalAuth = true